[tool.mypy]
namespace_packages = false
explicit_package_bases = false
disallow_untyped_defs = true

[tool.isort]
# profile = "black"
lines_after_imports = 2
force_single_line = true
group_by_package = true
ensure_newline_before_comments = true

[tool.black]
line-length = 88  # default
target-version = ['py310']
